dist: xenial

os: linux

language: java

jobs:
  include:
    - jdk: openjdk17
      env:
        - JDK='OpenJDK 17'
        - REDIS=unstable
    - jdk: openjdk17
      env:
        - JDK='OpenJDK 17'
        - PROFILE=jmh
    - jdk: openjdk17
      env:
        - JDK='OpenJDK 17'
        - REDIS=6.0
    - jdk: openjdk17
      env:
        - JDK='OpenJDK 17'
        - REDIS=5.0
    - jdk: openjdk17
      env:
        - JDK='OpenJDK 17'
        - REDIS=4.0
    - jdk: openjdk17
      env:
        - JDK='OpenJDK 17'
        - REDIS=3.2
    - env: JDK='OpenJDK EA'
      before_install: wget https://github.com/sormuras/bach/raw/master/install-jdk.sh && . ./install-jdk.sh
  allow_failures:
    - env: JDK='OpenJDK EA'

install:
  - if [[ ! -f downloads/stunnel-5.60.tar.gz ]]; then wget -O downloads/stunnel-5.60.tar.gz https://www.stunnel.org/downloads/stunnel-5.60.tar.gz; fi
  - if [[ ! -f ./stunnel-5.60/configure ]]; then tar -xzf downloads/stunnel-5.60.tar.gz; fi
  - if [[ ! -f ./stunnel-5.60/src/stunnel ]]; then cd ./stunnel-5.60; ./configure; make; cd ..; fi
  - export PATH="$PATH:$(pwd)/stunnel-5.60/src"
  - make prepare ssl-keys

script: make test-coverage PROFILE=${PROFILE:-ci}

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - '$HOME/.m2/repository'
    - 'downloads'
    - 'stunnel-5.60'

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7c2a962829d225c47a31
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
